version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_ENV=local
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: joel_dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: joel_dev_db
    ports:
      - "5432:5432"

volumes:
  postgres_dev_data:
