version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"  
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: joel_b
      POSTGRES_PASSWORD: my_blog89
      POSTGRES_DB: joel_postgres6

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf #Production
      #- ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf #Development
      - static_volume:/app/staticfiles
      - nginx_logs:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 1d & wait \$${!}; done"
    # The entrypoint is a placeholder; renewal will be handled by cron on the host.

volumes:
  static_volume:
  postgres_data:  
  nginx_logs:
  
