# Generated by Django 5.1.4 on 2025-10-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
